"""
services/task_processor.py
异步任务处理器
"""
import asyncio
import json
import os
import subprocess
import tempfile
from datetime import datetime

import httpx

from models.task import (
    Task,
    TaskStatus,
    TaskType,
    VideoStitchResult,
)
from services.task_store import task_store
from services.gcs_client import upload_video, generate_signed_url, download_blob
from services.firestore_client import save_landmark, db


class TaskProcessor:
    """任务处理器"""

    def __init__(self):
        self._running_tasks: dict[str, asyncio.Task] = {}

    async def process_video_clip(self, task: Task) -> None:
        """处理视频片段生成任务（Image-to-Video 模式）"""
        try:
            task_store.update_task(task)

            from services.wavespeed_api import generate_video_clip

            prompt = task.metadata.get("prompt", "")
            image_url = task.metadata.get("image_url", "")
            
            task.status = TaskStatus.PROCESSING
            task.progress = 10
            task_store.update_task(task)

            await asyncio.sleep(1)

            task.progress = 50
            task.estimated_time_remaining = 30
            task_store.update_task(task)

            video_url = await generate_video_clip(prompt, image_url)

            # Start GCS Upload & Firestore Update process
            landmark_id = task.metadata.get("landmark_id")
            
            task.progress = 60
            task.estimated_time_remaining = 20
            task_store.update_task(task)
            
            # Download the video generated by WaveSpeed
            work_dir = tempfile.mkdtemp(prefix="clip_")
            local_clip_path = os.path.join(work_dir, "temp_clip.mp4")
            async with httpx.AsyncClient(timeout=120.0) as client:
                response = await client.get(video_url)
                response.raise_for_status()
                with open(local_clip_path, "wb") as f:
                    f.write(response.content)
            
            task.progress = 70
            task.estimated_time_remaining = 15
            task_store.update_task(task)

            # Upload to GCS (path includes location_id / room_code)
            timestamp = int(datetime.now().timestamp())
            location_id = task.metadata.get("location_id", "USS")
            room_code_clip = task.metadata.get("room_code", "master")
            blob_name = f"{location_id}/{room_code_clip}/clips/clip_{landmark_id}_{timestamp}.mp4" if landmark_id else f"{location_id}/{room_code_clip}/clips/temp_{timestamp}.mp4"
            cloud_video_url = await upload_video(local_clip_path, blob_name)
            
            task.progress = 90
            task.estimated_time_remaining = 5
            task_store.update_task(task)
            
            # Save blob name to Firestore (preserves user's original prompt etc.)
            if landmark_id:
                await save_landmark(landmark_id, {"videoBlobName": blob_name})

            # Generate signed URL for the frontend (60 min validity)
            signed_video_url = generate_signed_url(blob_name, expiration_minutes=60)

            await asyncio.sleep(0.5)

            task.status = TaskStatus.COMPLETED
            task.progress = 100
            task.result = signed_video_url
            task.estimated_time_remaining = 0
            task_store.update_task(task)

        except Exception as e:
            task.status = TaskStatus.FAILED
            task.error = str(e)
            task_store.update_task(task)

    async def process_video_stitch(self, task: Task) -> None:
        """处理视频拼接任务"""
        try:
            video_urls = task.metadata.get("video_urls", [])
            video_blob_names = task.metadata.get("video_blob_names", []) or []
            work_dir = tempfile.mkdtemp(prefix="vlog_")
            output_path = os.path.join(work_dir, "final_vlog.mp4")

            task.status = TaskStatus.PROCESSING
            task.progress = 5
            task.total = len(video_urls) * 10 + 100
            task_store.update_task(task)

            local_files: list[str] = []
            for i, url in enumerate(video_urls):
                if not url:
                    continue

                # ── 解析 Blob 路径 ─────────────────────────────────────────
                # 优先使用前端传来的 video_blob_names；
                # 若没有，则从 GCS 签名 URL 中解析出 blob 路径（兜底）
                blob_name: str | None = (
                    video_blob_names[i] if i < len(video_blob_names) else None
                ) or None

                if not blob_name and url and "storage.googleapis.com" in url:
                    try:
                        from urllib.parse import urlparse
                        parsed = urlparse(url)
                        # path 格式: /bucket-name/blob-path
                        parts = parsed.path.lstrip("/").split("/", 1)
                        if len(parts) == 2:
                            blob_name = parts[1]  # 去掉 bucket 前缀
                    except Exception as parse_err:
                        print(f"[Stitch] URL 解析 blob 失败: {parse_err}")

                local_path = os.path.join(work_dir, f"clip_{i:03d}.mp4")

                if blob_name:
                    # ── 首选：GCS SDK 直连下载，零签名过期风险 ──────────
                    await asyncio.to_thread(download_blob, blob_name, local_path)
                else:
                    # ── 兜底：httpx 下载原始 URL（仅当无法获取 blob 路径时）
                    print(f"[Stitch] 无法获取 blob 名称，回退 HTTP 下载: {url[:80]}")
                    async with httpx.AsyncClient(timeout=120.0) as client:
                        resp = await client.get(url)
                        resp.raise_for_status()
                        with open(local_path, "wb") as f:
                            f.write(resp.content)

                local_files.append(local_path)
                task.progress = 5 + (i + 1) * 10
                task.estimated_time_remaining = max(0, 60 - (i + 1) * 5)
                task_store.update_task(task)

            if not local_files:
                raise RuntimeError("No valid video clips to stitch.")

            concat_list_path = os.path.join(work_dir, "concat_list.txt")
            with open(concat_list_path, "w", encoding="utf-8") as f:
                for file_path in local_files:
                    f.write(f"file '{file_path}'\n")

            # ── moviepy 升级拼接：转场 + 字幕 + BGM ──────────────────────
            task.progress = 80
            task.estimated_time_remaining = 30
            task_store.update_task(task)

            landmark_names = task.metadata.get("landmark_names", None)

            from services.video_stitcher import stitch_clips_moviepy
            await asyncio.to_thread(
                stitch_clips_moviepy,
                local_files,
                landmark_names,
                output_path,
            )

            # 获取实际时长（通过 ffprobe）
            duration = 0.0
            probe_cmd = [
                "ffprobe",
                "-v", "error",
                "-show_entries", "format=duration",
                "-of", "default=noprint_wrappers=1:nokey=1",
                output_path,
            ]
            probe_result = subprocess.run(
                probe_cmd, capture_output=True, text=True
            )
            if probe_result.returncode == 0:
                try:
                    duration = float(probe_result.stdout.strip())
                except ValueError:
                    duration = 0.0

            task.progress = 95
            task.estimated_time_remaining = 10
            task_store.update_task(task)

            timestamp = int(datetime.now().timestamp())
            room_code = task.metadata.get("room_code", "master")
            location_id = task.metadata.get("location_id", "USS")  # [Multi-location]
            blob_name = f"{location_id}/{room_code}/vlogs/vlog_{timestamp}.mp4"
            final_vlog_url = await upload_video(output_path, blob_name)
            
            if db:
                vlog_id = f"vlog_{timestamp}"
                vlog_data = {
                    "vlog_id": vlog_id,
                    "final_vlog_blob_name": blob_name,
                    "resolution": "1920x1080",
                    "duration": duration,
                    "clip_count": len(local_files),
                    "timestamp": timestamp,
                    "created_at": timestamp,
                    "title": f"Vlog - {datetime.fromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S')}",
                    "room_code": room_code,
                    "location_id": location_id,  # [Multi-location] 写入 Firestore
                }
                await db.collection("vlogs").document(vlog_id).set(vlog_data)

            # Generate a signed URL for the final vlog (60 min validity)
            final_signed_url = generate_signed_url(blob_name, expiration_minutes=60)

            stitch_result = VideoStitchResult(
                output_path=final_signed_url,
                resolution="1920x1080",
                bitrate="5M",
                duration=duration,
                clip_count=len(local_files),
            )

            task.status = TaskStatus.COMPLETED
            task.progress = 100
            task.result = json.dumps(stitch_result.to_dict())
            task.estimated_time_remaining = 0
            task.metadata["resolution"] = stitch_result.resolution
            task.metadata["bitrate"] = stitch_result.bitrate
            task.metadata["duration"] = stitch_result.duration
            task.metadata["clip_count"] = stitch_result.clip_count
            task.metadata["final_vlog_url"] = final_signed_url
            task_store.update_task(task)

        except Exception as e:
            task.status = TaskStatus.FAILED
            task.error = str(e)
            task_store.update_task(task)

    async def submit_task(self, task: Task) -> str:
        """提交任务"""
        task_store.create_task(task)

        if task.task_type == TaskType.VIDEO_CLIP:
            asyncio.create_task(self.process_video_clip(task))
        elif task.task_type == TaskType.VIDEO_STITCH:
            asyncio.create_task(self.process_video_stitch(task))

        return task.task_id


task_processor = TaskProcessor()
